# ~/.config/starship.toml

[character]
symbol = "❯"
color = "light-blue"  # Change to light blue

[directory]
style = "bold light-blue"  # Change the directory color to light blue

[git_status]
style = "light-green"  # Green for git status

[git_branch]
style = "light-purple"  # Purple for git branch

[line_break]
disabled = false

# Correcting the format section 
# Set format to a valid string with placeholders
format = "[$directory]($style) $character"
