[colors]
foreground = "#cbe3e7"
background = "#0c0f17"
cursor_bg = "#8aff80"
cursor_border = "#8aff80"
cursor_fg = "#0c0f17"
selection_bg = "#23476a"
selection_fg = "#ffffff"
ansi = ["#0c0f17", "#ff5c57", "#8aff80", "#f3f99d", "#57c7ff", "#ff6ac1", "#9aedfe", "#f1f1f0"]
brights = ["#686868", "#ff5c57", "#8aff80", "#f3f99d", "#57c7ff", "#ff6ac1", "#9aedfe", "#ffffff"]
