services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:8080"  # ← maps LXC's port 3000 to container's 8080
    environment:
      - OLLAMA_BASE_URL=http://10.0.0.21:11434
      - USER_AGENT=cktechx/ghostkellz
    volumes:
      - openwebui-data:/app/backend/data

volumes:
  openwebui-data:
